# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2933e0d92f9f0202b795d0eede3793af81214590892b7ef1d979d88922e21fd230d280aea278dbfa57c46476e5aad6c73604f3d27498f12c204311bb15e36cbb

test:
  secret_key_base: 1a4431dc00c15d94278e3f64c5b948e259673b280763d792d1ac7c920839bc6eacb227f71e0d9919f33e9f3585af90ccf3ba05dd5e8fe29ed7c15a51bfafd6c4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
